# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[mgr]
ratio          = [ 1, 4, 3 ]
sort_by = "natural"
sort_sensitive = false
sort_reverse 	 = false
sort_dir_first = true
sort_translit  = false
linemode       = "size_and_mtime"
show_hidden    = false
show_symlink   = true
scrolloff      = 5
mouse_events   = [ "click", "scroll" ]
title_format   = "Yazi: {cwd}"

[opener]
edit = [
	{ run = '${EDITOR} "$1"', desc = '$EDITOR', for = "unix", block = true },
]
play = [
  { run = 'explorer.exe "$(wslpath -w "$1")" &', desc = "Play", for = "linux" },
]
open = [
	{ run = 'explorer.exe "$(wslpath -w "$1")" &', desc = "Open", for = "linux" },
]
reveal = [
	{ run = 'explorer.exe /select,$(wslpath -w "$1") &', desc = "Reveal", for = "linux" },
]
extract = [
	{ run = "7z x $1", desc = "Extract here" },
]
download = [
	{ run = "ya emit download --open $1", desc = "Download and open" },
	{ run = "ya emit download $1",        desc = "Download" },
]

[open]
rules = [
	# Folder
	{ url = "*/", use = [ "edit", "open", "reveal"] },
	# HTML
	{ mime = "text/html", use = [ "open", "edit", "reveal" ] },
	# Text
	{ mime = "text/*", use = [ "edit", "reveal" ] },
	# Image
	{ mime = "image/*", use = [ "open", "reveal" ] },
	# Media
	{ mime = "{audio,video}/*", use = [ "play", "reveal" ] },
	# Archive
	{ mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", use = [ "extract", "reveal" ] },
	# JSON
	{ mime = "application/{json,ndjson}", use = [ "edit", "reveal" ] },
	{ mime = "*/javascript", use = [ "edit", "reveal" ] },
	# Empty file
	{ mime = "inode/empty", use = [ "edit", "reveal" ] },
	# Virtual file system
	{ mime = "vfs/*", use = "download" },
	# Fallback
	{ url = "*", use = [ "open", "reveal" ] },
]

